version: "3.7"

services:
  application:
    build:
      context: application
    environment:
      PRODUCTION: "TRUE"
      NODE_OPTIONS: "--max_old_space_size=4096"
    expose:
      - 443
    ports:
      - 443:443
      - 5173:5173
      - 4590:4590
    stdin_open: true
    #volumes:
      #- ./application:/usr/src/app
      #- /usr/src/app/node_modules
    restart: always
    networks:
      - express-mongo
    depends_on:
      - mongo
  mongo:
    restart: always
    image: mongo:8.0.0
    volumes:
      - mongo_data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
    logging:
      driver: "none"

networks:
  express-mongo:

volumes:
  mongo_data:
